const { Painting } = require('../models');

const paintingdata = [
  {
    title: 'Spring Orientation',
    artist: 'Central Jersey HQ',
    exhibition_date: 'March 30, 2018',
    gallery_id: 1,
    filename: '01-spring-events.jpg',
    description:
      'Spring Orientation will be held on March 20th, 2021 at our Central Jersey HQ, this will be a great opportunity to to meet other students and get an overview of our program',
  },
  {
    title: 'Kean University',
    artist: 'Union, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 1,
    filename: '02-kean-campus.webp',
    description: 'Kean University is a public university in Union and Hillside, New Jersey. It is part of New Jersey public system of higher education. Kean University is best known for its programs in the humanities and social sciences and in education, graduating the most teachers in the state of New Jersey annually.',
  },
  {
    title: 'Montclair State University',
    artist: 'Montclair, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 1,
    filename: '03-montclair-campus.jpg',
    description: 'Montclair State University is a public research university in Montclair, New Jersey, with parts of the campus extending into Little Falls, New Jersey. It is the second largest university in New Jersey',
  },
  {
    title: 'Rowan University',
    artist: 'Glassboro, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 1,
    filename: '04-rowan-campus.jpg',
    description: 'Rowan University is a public research university in Glassboro, New Jersey, with a medical campus in Stratford, New Jersey, and medical and academic campuses in Camden, New Jersey. It was founded in 1923 as Glassboro Normal School on a 25-acre site donated by 107 residents.',
  },
  {
    title: 'Rutgers University',
    artist: 'New Brunswick, NJ',
    exhibition_date: 'May 05, 2017',
    gallery_id: 1,
    filename: '05-rutgers-campus.jpg',
    description: 'Rutgers University–New Brunswick is one of three regional campuses of Rutgers University, New Jerseys public research university. It is located in New Brunswick and Piscataway. It is the oldest campus of the university, the others being in Camden and Newark.',
  },
  {
    title: 'The College of New Jersey',
    artist: 'Ewing, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 1,
    filename: '06-tcnj-campus.png',
    description: 'The College of New Jersey is a public university in Ewing, New Jersey. It is part of New Jerseys public system of higher education. TCNJ was established in 1855 as the New Jersey State Normal School. The institution was the first normal school in the state of New Jersey and the fifth in the United States.',
  },
  {
    title: 'Summer Orientation',
    artist: 'South Jersey HQ',
    exhibition_date: 'June 10, 2019',
    gallery_id: 2,
    filename: '01-summer-events.jpg',
    description: 'Summer Orientation to meet other students',
  },
  {
    title: 'Kean University',
    artist: 'Union, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 2,
    filename: '02-kean-campus.webp',
    description: 'Kean University is a public university in Union and Hillside, New Jersey. It is part of New Jersey public system of higher education. Kean University is best known for its programs in the humanities and social sciences and in education, graduating the most teachers in the state of New Jersey annually.',
  },
  {
    title: 'Montclair State University',
    artist: 'Montclair, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 2,
    filename: '03-montclair-campus.jpg',
    description: 'Montclair State University is a public research university in Montclair, New Jersey, with parts of the campus extending into Little Falls, New Jersey. It is the second largest university in New Jersey',
  },
  {
    title: 'Rowan University',
    artist: 'Glassboro, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 2,
    filename: '04-rowan-campus.jpg',
    description: 'Rowan University is a public research university in Glassboro, New Jersey, with a medical campus in Stratford, New Jersey, and medical and academic campuses in Camden, New Jersey. It was founded in 1923 as Glassboro Normal School on a 25-acre site donated by 107 residents.',
  },
  {
    title: 'Rutgers University',
    artist: 'New Brunswick, NJ',
    exhibition_date: 'May 05, 2017',
    gallery_id: 2,
    filename: '05-rutgers-campus.jpg',
    description: 'Rutgers University–New Brunswick is one of three regional campuses of Rutgers University, New Jerseys public research university. It is located in New Brunswick and Piscataway. It is the oldest campus of the university, the others being in Camden and Newark.',
  },
  {
    title: 'The College of New Jersey',
    artist: 'Ewing, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 2,
    filename: '06-tcnj-campus.png',
    description: 'The College of New Jersey is a public university in Ewing, New Jersey. It is part of New Jerseys public system of higher education. TCNJ was established in 1855 as the New Jersey State Normal School. The institution was the first normal school in the state of New Jersey and the fifth in the United States.',
  },
  {
    title: 'Fall Orientation',
    artist: 'DrivingJack',
    exhibition_date: 'October 15, 2018',
    gallery_id: 3,
    filename: '01-fall-events.jpg',
    description:
      'Fall Orientation to meet other students',
  },
  {
    title: 'Kean University',
    artist: 'Union, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 3,
    filename: '02-kean-campus.webp',
    description: 'Kean University is a public university in Union and Hillside, New Jersey. It is part of New Jersey public system of higher education. Kean University is best known for its programs in the humanities and social sciences and in education, graduating the most teachers in the state of New Jersey annually.',
  },
  {
    title: 'Montclair State University',
    artist: 'Montclair, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 3,
    filename: '03-montclair-campus.jpg',
    description: 'Montclair State University is a public research university in Montclair, New Jersey, with parts of the campus extending into Little Falls, New Jersey. It is the second largest university in New Jersey',
  },
  {
    title: 'Rowan University',
    artist: 'Glassboro, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 3,
    filename: '04-rowan-campus.jpg',
    description: 'Rowan University is a public research university in Glassboro, New Jersey, with a medical campus in Stratford, New Jersey, and medical and academic campuses in Camden, New Jersey. It was founded in 1923 as Glassboro Normal School on a 25-acre site donated by 107 residents.',
  },
  {
    title: 'Rutgers University',
    artist: 'New Brunswick, NJ',
    exhibition_date: 'May 05, 2017',
    gallery_id: 3,
    filename: '05-rutgers-campus.jpg',
    description: 'Rutgers University–New Brunswick is one of three regional campuses of Rutgers University, New Jerseys public research university. It is located in New Brunswick and Piscataway. It is the oldest campus of the university, the others being in Camden and Newark.',
  },
  {
    title: 'The College of New Jersey',
    artist: 'Ewing, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 3,
    filename: '06-tcnj-campus.png',
    description: 'The College of New Jersey is a public university in Ewing, New Jersey. It is part of New Jerseys public system of higher education. TCNJ was established in 1855 as the New Jersey State Normal School. The institution was the first normal school in the state of New Jersey and the fifth in the United States.',
  },
  {
    title: 'Winter Orientation',
    artist: 'Vlad Sokolovsky',
    exhibition_date: 'December 24, 2020',
    gallery_id: 4,
    filename: '01-winter-events.jpg',
    description:
      'Winter Orientation to meet other students',
  },
  {
    title: 'Kean University',
    artist: 'Union, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 4,
    filename: '02-kean-campus.webp',
    description: 'Kean University is a public university in Union and Hillside, New Jersey. It is part of New Jersey public system of higher education. Kean University is best known for its programs in the humanities and social sciences and in education, graduating the most teachers in the state of New Jersey annually.',
  },
  {
    title: 'Montclair State University',
    artist: 'Montclair, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 4,
    filename: '03-montclair-campus.jpg',
    description: 'Montclair State University is a public research university in Montclair, New Jersey, with parts of the campus extending into Little Falls, New Jersey. It is the second largest university in New Jersey',
  },
  {
    title: 'Rowan University',
    artist: 'Glassboro, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 4,
    filename: '04-rowan-campus.jpg',
    description: 'Rowan University is a public research university in Glassboro, New Jersey, with a medical campus in Stratford, New Jersey, and medical and academic campuses in Camden, New Jersey. It was founded in 1923 as Glassboro Normal School on a 25-acre site donated by 107 residents.',
  },
  {
    title: 'Rutgers University',
    artist: 'New Brunswick, NJ',
    exhibition_date: 'May 05, 2017',
    gallery_id: 4,
    filename: '05-rutgers-campus.jpg',
    description: 'Rutgers University–New Brunswick is one of three regional campuses of Rutgers University, New Jerseys public research university. It is located in New Brunswick and Piscataway. It is the oldest campus of the university, the others being in Camden and Newark.',
  },
  {
    title: 'The College of New Jersey',
    artist: 'Ewing, New Jersey',
    exhibition_date: 'May 05, 2017',
    gallery_id: 4,
    filename: '06-tcnj-campus.png',
    description: 'The College of New Jersey is a public university in Ewing, New Jersey. It is part of New Jerseys public system of higher education. TCNJ was established in 1855 as the New Jersey State Normal School. The institution was the first normal school in the state of New Jersey and the fifth in the United States.',
  },
];

const seedPaintings = () => Painting.bulkCreate(paintingdata);

module.exports = seedPaintings;
